### ISSUE TITLE
"--query" option does not work if the specified image is not contained in the target_dir

### ISSUE THREAD

**Issue by zerobikappa** [knjcode/imgdupes#53]
directory like this:

directory1/
......├── 1.png
......└── directory2
.........................└── 1.copy.png

If I cd to directory1/  then run:
`imgdupes -r . --query 1.png dhash 4`

It would show the result:

`Searching similar images                              `
`100%|████████████| 2/2 [00:00<00:00, 15335.66it/s]`
`Query: 1.png`

`1.png`
`directory2/1.copy.png`

However, if I run:
`imgdupes -r directory2 --query 1.png dhash 4`

It would fail to find out the 1.copy.png :

`Searching similar images                              `
`100%|████████████| 1/1 [00:00<00:00, 3342.07it/s]`
`Query: 1.png`

**Comment by knjcode** [comment]
Hi @zerobikappa 
Thank you for your feedback. I will check and fix this issue.

**Comment by knjcode** [comment]
Hi @zerobikappa 
I have just released a bug fix version. (0.0.24)
